### ISSUE TITLE
Changing the Board from AVR to ARM

### ISSUE THREAD

**Issue by AlirezaSadri** [Sloeber/arduino-eclipse-plugin#1011]
Hi

I was working with Mega2560 and wanted to use a STM-Nucleo-ARM board. So I just changed the board in the properties of the project. Then when I had instances for adafruit lcd or hardware serial I would get the following error:

Adafruit_ST7735 lcd = Adafruit_ST7735(CS,  DC, RST);
HardwareSerial STMSerial1(PA10, PA9);
HardwareSerial STMSerial2(PC7, PC6);

error:
"The type 'HardwareSerial' must implement the inherited pure virtual method 'Print::write'"

So, I just started a new ARM based project and imported all the other files from the previous project into the new one and then it was fine. why isn;t just changing the board enough?

Best regards
Alireza

**Comment by jantje** [comment]
Because there may be incompatible/unneeded libraries. Sloeber does not re-evaluate the libraries from scratch. Only the hardware specific libraries are changed.
You can delete the libraries folder to force a re-evaluation of the libraries.
If you want to use configurations you need to use exclude from build.
