### ISSUE TITLE
"Cannot find platform" is looking for 1.6.19 but 1.6.23 installed

### ISSUE THREAD

**Issue by pork-pie-hat** [Sloeber/arduino-eclipse-plugin#1032]
I just reinstalled my laptop to Windows 10 and now I can't get Sloeber working again.. I downloaded Eclipse C++ (v. 4.9.0) as zip, unpacked it in C:\Software\eclipse, started Eclipse as administrator, and installed Sloeber via the Marketplace. The workspace is set to C:\Users\<username-without-spaces>\eclipse-workspace. This configuration worked before on Windows 7.

When I want to configure my project, it pops up the error:
`failed to find the platform C:\Software\eclipse\arduinoPlugin\packages\arduino\hardware\avr\1.6.19\platform.txt\nDid you deinstall the platform?\nDid you import a project and did not install the platform?`

In the installation folder I can see that Sloeber installed avr version 1.6.23, so it's looking for the wrong path. How can I fix this?

Other, slightly annoying thing: I opened two previous projects (after installing Sloeber). One is directly recognised as Arduino project, the other one isn't. Any idea why?

Thanks in advance for the help!

**Comment by jantje** [comment]
Like the error states: You imported a project in a new eclipse installation and did not install the platform.

You have 2 options
1)Keep using the sketch with arduino avr version 1.6.19: Go to the Sloeber boards manager (menu->arduino->preferences) and install platform arduino avr version 1.6.19.
2) upgrade the sketch to 1.6.23:  Goto project properties and change the used board from arduino\hardware\avr\1.6.19 to arduino\hardware\avr\1.6.23

The reason this happens is because 
1)Sloeber installs the latest available arduino avr if no platforms are found. 
2)Sloeber support multiple platform versions.
3)Sloeber is not linked to (arduino) platform releases 

>Other, slightly annoying thing: I opened two previous projects (after installing Sloeber). One is directly recognised as Arduino project, the other one isn't. Any idea why?

no
