### ISSUE TITLE
Cannot change [-Wunused-parameter] warning level from gui

### ISSUE THREAD

**Issue by BriscoeTech** [Sloeber/arduino-eclipse-plugin#1216]
Hello Everyone,

I noticed that I am generating [-Wunused-parameter] as a warning in my project, and wanted to customize the warning level for this type .

Looking in [Properties] -> [C/C++ General] -> [Code Analysis] this option does not show in the menu. I am unable to right click the warning in the Problems Tab and customize the error level.

It would be a nice feature to add this as a option to also be customized.

**Comment by jantje** [comment]
Rereading this it is actually not a Slmoeber improvement request.

My current thinking: CDT shows errors/warnings provided by CDT codan and the gcc build output.
gcc created warnings are based on the command line which are defined by the arduino framework.
As you can not disable them in codan I assume the warning comes from gcc and as such it should be fixed with a compile directive or compile command.
