### ISSUE TITLE
When will this be fixed?

### ISSUE THREAD

**Issue by cahhoffman** [Sloeber/arduino-eclipse-plugin#1292]
**Describe the bug**
Any idea where to find the boards file for Arduino nRF52. On both mac and windows get same following error. Failed to install [DEPRECATED] Arduino mbed-enabled Boards Failed to download "http://downloads.arduino.cc/cores/ArduinoCore-mbed-nonexistant.tar.bz2".

**Comment by wm1962** [comment]
I get the same error. Is there any solution?

**Comment by FranzDurst** [comment]
Same here. Wanted to try Sloeber for the first time and neither recommended IDE nor Eclipse plugin works. At finishing Installation phase the mentioned ([DEPRECATED] ....) massage arises. Later it's not possible to create a new sketch due to "no boards.txt found". 
Tried on a different, "clean" computer --> same problem.

**Comment by jandrassy** [comment]
Arduino removed version 1.2 of mbed boards. 
install 1.3

**Comment by FranzDurst** [comment]
jandrassy, thanks a lot!
Found out that this is a known issue (with Arduino, not directly Soeber). [Issue](https://github.com/Sloeber/arduino-eclipse-plugin/issues/1264)

So just a minor glitch but can confuse you a lot if new to Soeber.

**Comment by wm1962** [comment]
Thanks a lot
