### ISSUE TITLE
Similarly named json repositories causing package download failure

### ISSUE THREAD

**Issue by BriscoeTech** [Sloeber/arduino-eclipse-plugin#1365]
Hello Everyone,

Found a bug that has to do with multiple repositories that have the same name, and is causing download package errors in the Platform and Boards manager

Windows 10
Sloeber v4.4

I currently have two repositories for the esp32 development, one is the stable releases, and the other are the release candidates for cutting edge development like the esp32-s2. I have them both listed in my third party index url's

release candidates: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json
stable released: https://dl.espressif.com/dl/package_esp32_index.json

![image](https://user-images.githubusercontent.com/23386254/127212137-9eda8368-22bc-4fef-bbc2-59512cf9218e.png)

When opening up the Platform and Boards manager, it appears that only one or both combined are being shown under the esp32 category. Its hard to tell, since the release candidate repo also has the major releases. For this example I want to install 1.0.5. When checking the box and then hitting apply, the download occurs and it appears to have installed the package
![image](https://user-images.githubusercontent.com/23386254/127212302-c99ed32d-0ffc-4498-9f7a-6a2571153ad1.png)

Bad news is that the folder was created and then removed when the installation was completed. If you view the folder during the installation progress, 1.0.5 it is there, but is then deleted when the installation completes.
![image](https://user-images.githubusercontent.com/23386254/127212497-186ed6b5-292d-46fc-9d58-a277d68a4e5c.png)

Current work around is to not have both repositories in the third party index section, and then the installation works properly.

It would be nice to have the different repositories show up as different esp32 dropdowns in the Platform and Boards manager to help prevent confusion on what version of the library is coming from what repository. This will also help future proof people who fork repositories and they have the same names as other mainline repositories.

**Comment by jantje** [comment]
There are a couple of issues here

First of all according to the Arduino specification https://arduino.github.io/arduino-cli/latest/package_index_json-specification/
A package should be named 
package_YOURNAME_PACKAGENAME_index.json
So https://dl.espressif.com/dl/package_esp32_index.json should be
https://dl.espressif.com/dl/package_.espressif_esp32_index.json

This has bugged me a lot because dfrobot provides https://git.oschina.net/dfrobot/FireBeetle-ESP32/raw/master/package_esp32_index.json and then the last downloaded is the only one available to sloeber


>When opening up the Platform and Boards manager, it appears that only one or both combined are being shown under the esp32 category. Its hard to tell, since the release candidate repo also has the major releases. 

It is easy to tell if you disable the "hide 3rd party json" files. 

> since the release candidate repo also has the major releases

If so I would advice not to use both. 

>Bad news is that the folder was created and then removed when the installation was completed. If you view the folder during the installation progress, 1.0.5 it is there, but is then deleted when the installation completes.

As platforms are removed/installed because of the check boxes and for one json you say install and for the other you say remove it depends on the order whether it will be available in the end.
Seems perfectly fine to me.

>Current work around is to not have both repositories in the third party index section, and then the installation works properly.

This is not a workaround. You should not have 2 json's providing the possibility to install the same platform versions.
