### ISSUE TITLE
indexing

### ISSUE THREAD

**Issue by nicoverduin** [Sloeber/arduino-eclipse-plugin#1402]
Once upon a long time ago.... Jantje explained how to avoid unresolved functions. Mea culpa but I forgot how (must be age). I know it was reindexing  but how do I set those options?
Regards
Nico

**Comment by jantje** [comment]
Hi Nico
Are you using the new ESP32 version? I ask because there is a discovery (add that word to your vocabulary ;-) ) issue
If you have a multiconfig environment you need to go to windows->preferences->C/C+->indexer. Though I heard the default changed it may be ...
![afbeelding](https://user-images.githubusercontent.com/1175841/140065778-4acb700e-89bf-4c3e-aba1-daa0e0ecda32.png)
If all this fails I need more specific info

**Comment by nicoverduin** [comment]
Seems to work now. So we can leave it as it is.
thx
