### ISSUE TITLE
Ordering of boards.txt is not respected in "project"->"properties"->"sloeber"->"board part number"

### ISSUE THREAD

**Issue by PerennialNovice** [Sloeber/arduino-eclipse-plugin#1450]
When selecting a board from the sloeber - properties menu, all the boards are listed randomly, which is not a big problem in most cases, but when playing around with STM32 generic variants, there are often dozens of boards which makes it quite difficult to find a specific one

![image](https://user-images.githubusercontent.com/85557472/155696385-467d3047-110e-4da3-938d-fbecf6270f14.png)

I am aware that this is rather a "cosmetic" issue, but I have a small hope that it is merely a small change that is necessary...
I really am only a novice programmer, but if someone points me to the specific location in the code, I could have a look and try to make up a fix?

**Comment by MasteringTheMess** [comment]
yes very similar, if not a duplicate.
I just checked the ESP8266 RAM size option and it is similarily random-ordered, but in a different way :)

I run a somewhat recent nightly 4.4.1
![image](https://user-images.githubusercontent.com/85557472/155715019-f74f7d06-a07e-40a2-9e2c-d95bd54bc875.png)

I could upgrade to the most recent for testing purpose if that helps?

**Comment by jantje** [comment]
I think this is fixed in V5
![image](https://github.com/user-attachments/assets/01c1add6-e554-40d0-afff-fe9ea529d201)

**Comment by vvs42** [comment]
I've been using Slobber since version 4.4.0 and haven't seen a solution to this problem in any version. Which version 5 are you talking about?

<img width="664" height="172" alt="Image" src="https://github.com/user-attachments/assets/79587f47-b2ff-4223-887a-c6b33e6c4437" />
<img width="791" height="717" alt="Image" src="https://github.com/user-attachments/assets/2036e0b8-2e23-425b-84b5-28675a386930" />
