### ISSUE TITLE
Esp32 compilation error

### ISSUE THREAD

**Issue by xiezhoubin** [Sloeber/arduino-eclipse-plugin#1469]
![3H1K2K~1000 EGTDG1RTRP](https://user-images.githubusercontent.com/75734559/169478289-a6793c04-0a9a-451d-857b-f95a49802a12.png)
![4WQ@0CBK UU4)326OE~QA4T](https://user-images.githubusercontent.com/75734559/169478333-62d047ea-7170-4c76-b103-3adf2fe2f9df.png)

**Comment by xiezhoubin** [comment]
![image](https://user-images.githubusercontent.com/75734559/169505354-53c17f5c-800c-4c70-8cf0-59b29cd59d1b.png)

**Comment by jantje** [comment]
There is nothing I can do about download issues. If you do not have the json file (because of failed download or failed processing) you are likely to experience path issues as on the first image you provided

Some textual description on what you did and what the problem seems to be like would be great.
Without that I can only do guesses.
This is why we added the content below to the new issue template:


**Before creating a bug report check for existing issues**  
Make sure you are on the latest and greatest Sloeber version. We do not support older version.  
Here is a list of [known limitations](https://github.com/Sloeber/arduino-eclipse-plugin/issues?q=is%3Aissue++label%3A%22status%3A+known+limitation%22+)   
Here is a list of [common issues ](https://github.com/Sloeber/arduino-eclipse-plugin/issues?q=is%3Aissue+label%3A%22Hot+issue%22+)   
Here is the list of all [open issues](https://github.com/Sloeber/arduino-eclipse-plugin/issues?q=is%3Aissue+is%3Aopen)  
Here is a list of issues that have been [fixed but are not yet available in a release](https://github.com/Sloeber/arduino-eclipse-plugin/issues?q=label%3A%22status%3A+fixed+in+nightly%22+)  

---

**Describe your environment**   
Do you use the Sloeber product or plugin?   
Sloeber version number  
OS: [e.g. windows 10]   
The url of the json that you used to download the platform  
A image of the project properties arduino showing the board settings   

**Describe the bug**   
A clear and concise description of what the bug is.

**To Reproduce**   
Steps to reproduce the behavior:   
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

provide the name of the board and the platform version you are using.  
Provide the json url and a screenshot of project properties->arduino  


**Expected behavior**   
A clear and concise description of what you expected to happen.  

**Data to back up your claim**   
If applicable, add screenshots, console output and/or logs to help explain your problem.   


**Additional context**   
Add any other context about the problem here.
