### ISSUE TITLE
SrcWrapper.h: No such file or directory - It still persists: "locked as resolved"

### ISSUE THREAD

**Issue by rtek1000** [Sloeber/arduino-eclipse-plugin#1538]
@rtek1000 please do not resurrect old issues.

_Originally posted by @jantje in https://github.com/Sloeber/arduino-eclipse-plugin/issues/1143#issuecomment-1365301731_
      

"locked as resolved and limited conversation to collaborators"

        It still persists:

> Arduino.h:33:12: fatal error: SrcWrapper.h: No such file or directory

(eclipse/embedcpp-2022-03/eclipse/arduinoPlugin/packages/STMicroelectronics/hardware/stm32/2.4.0)

P.S.: Since it failed to automatically install the STM32 core, so I copied the STM32 functional installation folder in the Arduino IDE to the eclipse folder.

_Originally posted by @rtek1000 in https://github.com/Sloeber/arduino-eclipse-plugin/issues/1143#issuecomment-1364761027_

**Comment by jantje** [comment]
> so I copied the STM32 functional installation folder in the Arduino IDE to the eclipse folder.

Do not do so unless you are a experienced user and understand about the Arduino framework or have detailed instructions of how to do it.
STM32 can be installed the normal way.

SrcWrapper.h is a library that should be auto magically included but that inclusion is based on the indexer working properly #1491 and #1534 both degrade the indexer working
You can manually add the library to the project (using the Sloeber menu) but for a reasonable Sloeber experience with STM32 you will need

1. the nightly release or at least anything since #1491
2. the workaround described in #1534

And no the problem fixed in #1143 does not persist.
