### ISSUE TITLE
V5.0 Sloeber "drops" the library selection when it is closed/restarted. 

### ISSUE THREAD

**Issue by jantje** [Sloeber/arduino-eclipse-plugin#1695]
The libraries are still in the project folder, but the previous selection when adding libraries to a project is lost.

As reported in issue #1694 by @TrippyLighting

![image](https://github.com/user-attachments/assets/e8f40fda-3ee3-44b8-ac20-1c4eed89cc05)

Looking at this I also see in V5 there is a need for add to all configurations option.
I think the current code only adds to the current configuration.

**Comment by TrippyLighting** [comment]
I can confirm that this has been fixed and works as expected on macOS and Windows 11. Thank You!

**Comment by jantje** [comment]
Thanks for confirming.

**Comment by TrippyLighting** [comment]
On MacOS (I've not tried it on Windows), Sloeber V5 still drops some libraries! I have yet to find a pattern, which might be due to my not knowing how this works under the hood.

It does not drop all of the libraries, just some. I will possibly start to screen record sessions when I compile successfully, close Sloeber, and open it up again so I can share what is happening.
