### ISSUE TITLE
Unable to upload sketch to Esplora board: "Leonardo upload port is not disappearing after reset"

### ISSUE THREAD

**Issue by kigster** [Sloeber/arduino-eclipse-plugin#173]
If I understand correctly, with Esplora IDE needs to briefly connect at 1200b to reset the board, and then upload. 

Using Arduino IDE 1.5.6-r2 I am able to upload my sketch to Esplora, but in Eclipse I get this error. After this error, it still tries to run avrdude, and that fails with the following output.

How can I get eclipse plugin to properly reset the board before uploading?

Many thanks for the wonderful plugin – I am using it with other Arduino boards without any problems, and I _love_ it!  It's so much better than the built in IDE, hopefully I can resolve this issue also :)

```
Starting upload
using arduino loader


Launching /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avrdude -C/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/etc/avrdude.conf -patmega32u4 -cavr109 -P /dev/cu.usbmodem1d1341 -b57600 -D -Uflash:w:/Users/kig/projects/eclipse/esplora_controller/Release/esplora_controller.hex:i 
Output:

Connecting to programmer: .avrdude: butterfly_recv(): programmer is not responding
avrdude finished
upload done
```

**Comment by davidlevinson** [comment]
I have a clean installation of Eclipse Neon + Eclipse Arduino v3 Plugin + Leonardo board + MacOS 10 + Arduino IDE 1.6.5.  

There is a bug in the "reset" process during the upload. Whatever steps are happening in "Starting reset using 1200bps touch process", this is not correctly resetting the board. In order to get a sketch to upload I need to click the reset button shorty after seeing the first PORTS output. Otherwise, I will get a "Connecting to programmer: .avrdude: butterfly_recv(): programmer is not responding" error. 

Perhaps there is a way to skip this step?
