### ISSUE TITLE
Hex file not being created

### ISSUE THREAD

**Issue by MrCredible** [Sloeber/arduino-eclipse-plugin#22]
I haven been away from my project for a couple months, but everything should still work as I left it.
For some reason now, I keep receiving the error that the hex file is not being created.
I clean my entire project and build all, but still receive the same issue.

I then created a new project using instructions @ http://www.baeyens.it/eclipse/UsethePlugin.html .
This still leads to the same issue. Any tips?

**Comment by butnarut** [comment]
I have the same issue in version 4.0. The path for all tools/workspace have no space in name.
The problem seems to be the make all command. In the log all steps are reported to be correctly finished, but in reality the release folder don't contain any object generated. If I manually run line by line the commands printed in the log file everything will be correctly compiled in the Release folder. Running in console the command make all will have the same result like started from editor: no output in release folder. Attached the output log file.
[test1.build.log.zip](https://github.com/Sloeber/arduino-eclipse-plugin/files/806258/test1.build.log.zip)

**Comment by jantje** [comment]
As you do not have spaces in the path this is not the same problem

**Comment by butnarut** [comment]
Hi,
I try also the latest nightlight and the result is the same.. no output generated in release folder.
It work fine if I manually run each line generated by the make program, copied from console or log file.
I try also with ESP8266 platform and the result is the same..

Attached the entire workspace with output from make all command.
[sloeber-workspace.zip](https://github.com/Sloeber/arduino-eclipse-plugin/files/810411/sloeber-workspace.zip)

**Comment by jantje** [comment]
please open new issue
mention your os, os version, os architecture, java version, java architecture, sloeber product or plugin and patreon id

**Comment by denzel-mapp** [comment]
Hello Community,

If you are as stressed as I was as to figuring out why your netbeans ide was not generating your hex file for arduino, I was able to solve my problem! If you followed the configuration instructions for getting netbeans to run arduino found at this link http://plugins.netbeans.org/plugin/46054/arduino , then you probably had this problem.

**Comment by nadinehany1** [comment]
> I keep getting the same error on my mac; hex file is not created. Anybody got a solution to this?
> ![schermafbeelding 2014-10-22 om 20 38 46](https://cloud.githubusercontent.com/assets/6529781/4754870/4d40ac28-5ac1-11e4-82b8-577f5e7cd693.png)
> 

I had the same problem and the instructor advised me to change its workspace directory. I was putting the workspace in d: and changed it to c:
But I guess It's because it's path was too long and then it became short.

**Comment by jantje** [comment]
I don't know what is the problem you are facing but I see following things that are of concern
1)Switch to the Arduino perspective
2) you should not have a Arduino.h in your project folder
3) you have arduino/core and that should be core/core
In other words it looks like you are not running Sloeber but some other program.
