### ISSUE TITLE
incorrect Arduino IDE version detection

### ISSUE THREAD

**Issue by cdcooperuk** [Sloeber/arduino-eclipse-plugin#32]
This is related to https://github.com/jantje/arduino-eclipse-plugin/issues/11

On ubuntu 13.04, the plugin has determined the Arduino IDE Version to be "1:1.0.5+dfsg-2" (this is displayed in the Arduino-Arduino preferences page, but is not editable)

This gets passed thru to the compile flags as  "-DARDUINO=1:105+dfsg2-1"

Then during compilation the ":" and other special characters give a syntax error in the standard external library version check "#if ARDUINO < 100"

A workaround is to override the project's Build Variable ARDUIONO_IDE_VERSION to simply "105" in project settings.

Further info: on another machine, the ide version is simply detected as "1.0.3" and passed thru as "103", despite the installed package version being "1:1.0.3+dfsg-2".  I have no idea why one is is simplified and the other is not.

**Comment by otzen** [comment]
I have a problem with this too
I use the debian packaged versio of the IDE, ( I know You reccomend the non dist version, but anyhow)

here the string in version.txt is

    2:1.5.6.2+sdfsg2-3
This leads project will not build because the commandline to compiler now contains

    -DARDUINO=2 1.5.6.2+sdfsg2-3
Note the space. And gives an error that gcc can't find the file `1.5.6.2+sdfsg2-3`

I Downloaded the version from arduino.com, and looked in version.txt here it contains

    1.5.6-r2
resulting in 

    -DARDUINO=156-r2
This will build (only tried the blink sctech so far)
But I think the result must be

    -DARDUINO=156
I suggest to take a look at the arduino makefiel project (arduino-mk) in debian, this makefile also graps the version number from version.txt, and commes up the right result. On all tree types of strings

    sed -e 's/^[0-9]://g' -e 's/[.]//g' -e 's/$$/0000/'| head -c3
I tried feeding this with

 -   2:1.5.6.2+sdfsg2-3
 -   1.5.6-r2
 -   1.5.6

And they all return 156

**Comment by jantje** [comment]
Arduino IDE 1.6.5 uses -DARDUINO=10605
and so does the latest version (=nightly) of the plugin.
