### ISSUE TITLE
Absolute paths in .project file prevent sharing of Arduino projects

### ISSUE THREAD

**Issue by neuweiler** [Sloeber/arduino-eclipse-plugin#34]
When more than one developer is working on a project (e.g. like on https://github.com/neuweiler/GEVCU ) some path variables are stored in the .project file which usually could be shared in a repository. Although one sets the arduino paths in global preferences, they are stored in the .project file and not in the workspace settings:

Here's an excerpt of my .project file:

```
<variableList>
<variable>
<name>ArduinoHardwareLibPath</name>
<value>file:/Z:/development/arduino/arduino-1.5.2/hardware/arduino/sam/libraries</value>
</variable>
<variable>
<name>ArduinoPinPath</name>
<value>file:/Z:/development/arduino/arduino-1.5.2/hardware/arduino/sam/variants</value>
</variable>
<variable>
<name>ArduinoPlatformPath</name>
<value>file:/Z:/development/arduino/arduino-1.5.2/hardware/arduino/sam</value>
</variable>
</variableList>
```

Is it possible to move these to another location so the .project file can be shared on different platforms like it is the case with standard eclipse projects?

**Comment by jantje** [comment]
I think I found a solution to this. :-)

With the new Arduino IDE less plugin I no longer use the linked resources but link directly to the actual path on the system.
This is a real problem for version control because now all disk locations used must be on the same location for all users of a shared project (due to this info being in the .project file).
To avoid this I was thinking: If one would create workspace linked resources I could look for the "most matching linked resource" If none is found there will be a full path link
If one is found the link is made starting from the workspace level linked resource.

That means that as a project you can decide on the number, names, locations of the "workspace level linked resources" and any project member can have them on a different location.
So you guys don't need me :-)

The only part I expect to have to change for this to work is:
https://github.com/jantje/arduino-eclipse-plugin/blob/bigChange/it.baeyens.arduino.core/src/it/baeyens/arduino/tools/ArduinoHelpers.java#L247

If you look at the "old" implementation it should be pretty clear what needs to be done.
https://github.com/jantje/arduino-eclipse-plugin/blob/master/it.baeyens.arduino.core/src/it/baeyens/arduino/tools/ArduinoHelpers.java#L244

Input is welcomed.

**Comment by jantje** [comment]
I just fixed #463 and I think this fixes this problem as well.
Because you can add path variables at the workspace level (in windows->preferences->general->workspace->linked resources) and these will be used to replace the start of locations stored in .project files you can easily reference completely different locations (even different OS'es). For instance I created a GIT reference to point to the root of my GIT repositories and a TEENSY to point to my teensy install.
If I share this project including the .project file and someone clones the repository and pits GIT and TEENSY to the respective locations on his system then he can use the project without any further changes.

**Comment by olowo726** [comment]
Running 4.0 I found two issues in .settings/org.eclipse.cdt.core.prefs with prevented me from sharing projects.

1. Sometimes the absolute path to eclipse installation is used instead of eclipse variable. For example
....A.RECIPE.C.COMBINE.PATTERN.1/value="C\:\\eclipse\\/arduinoPlugin.... should be
....A.RECIPE.C.COMBINE.PATTERN.1/value="${eclipse_home}/arduinoPlugin.....
2. Absolute path to products used in some cases. For example in A.RECIPE.C.COMBINE.PATTERN.1/value the absolute path to the map file is used. I replaced it with ${A.BUILD.PATH}/${A.BUILD.PROJECT_NAME}.map and then we could share our projects.

**Comment by jantje** [comment]
The A.RECIPE.XXX.PATTERN.[number] are absolute on purpose.

**Comment by olowo726** [comment]
Why is that? The absolute paths to build products prevents us from having our project in different directories and the absolute path to the eclipse installations forces us to install eclipse in the same location on all machines (uniformity in the team is often a good thing but hard to enforce).

**Comment by jantje** [comment]
That is because of the parsing that needs to be done in expanded format. I've written a long explanation about this somewhere not so long ago but I can't remember where.

**Comment by jantje** [comment]
I think this issue is fixed if you create path variables for all locations used.

**Comment by jantje** [comment]
I declare this issue fixed. Please reopen if not fixed.
