### ISSUE TITLE
How to debug FreeRTOS 

### ISSUE THREAD

**Issue by shineviayan** [Sloeber/arduino-eclipse-plugin#647]
I want to use Sloeber to compile and debug FreeRTOS Task on Arduino Due.
Is this supported ? All pointers are welcome

Thanks in advance
-Shine

**Comment by jantje** [comment]
As far as I know the due has no native feature to debug.
So this would require a debugger.

**Comment by freeck** [comment]
I have adopted a very pragmatic solution for in my case debugging ArduinoMini boards (this board only supports SWD- instead of JTAG-interface):
- buy an AtmelICE module (or any other compatible ICE for your processor supported by AtmelStudio)
- edit/compile/build with Sloeber (C/C++ build option set at -ggdb -o0)
- thereby creating a "elf" file
- start AtmelStudio, open the objectfile you just created
- start debugging!

**Comment by jantje** [comment]
@freeck 
There must be a better way. But lets discuss during the esp32 debug I want to start early next year

**Comment by freeck** [comment]
That's what I though , but the SWD-protocol seems to be proprietary....
