### ISSUE TITLE
Sloeber tries to compile [assembly].asm where Arduino uses [assembly].S file directly

### ISSUE THREAD

**Issue by ligius-** [Sloeber/arduino-eclipse-plugin#660]
Using V3 from the marketplace.
I'm trying to compile the Digispark examples which provide USB support, via some assembly instructions. For example the DigisparkJoystick library.

The first issue is that usbdrvasm.asm file has an "end" instruction at the end which is somehow not recognized.

The second issue is that inside the usbdrvasm.S file the #if blocks are not recognized (preprocessor is not working).

Even after the two issues above are manually fixed (by removing code) some new problems appear, which leads me to think that the avr assembler is not used.

If this is specific to my setup I will be happy to attach any details.

**Comment by jantje** [comment]
Oeps I forgot to update the market place.
Lots of changes were done in V4 to add support for lots of boards.

**Comment by jantje** [comment]
I updated the marketplace

**Comment by ligius-** [comment]
I removed the old plugin, updated to 4.0, reconfigured the plugin but the issues above still remain.
I've created a pastebin with the output from Arduino IDE vs. Eclipse: http://pastebin.com/QUdvFYP8

**Comment by jantje** [comment]
Thanks for the pastebin info.
From that info you can see that the Arduino IDE does not try to compile usbdrvasm.asm.
I do not know what the current criteria are the Arduino IDE uses to not compile and use the usbdrvasm.S file directly.
Anyway you can tell Sloeber to use the S file instead of the .asm file in 2 ways.
in the project explorer go to you project/libraries/DigiSparkMouse
Right click the usbdrvasm.asm file and select
1) delete to fix this problem for this sloeber installation.
2)resource configuration->exclude from build->select all->ok to fix the problem for your current project

As an independent open source project we value your submission, but we ask for support, either by helping us out coding (yeah, we do understand it does require time) or a Patreon contribution (starting from as low as 1$ a month): this allows us to support people who support us back!
As a supporter you can drag our attention and prioritize your submission...
please become a supporter!
https://www.patreon.com/jantje

**Comment by jantje** [comment]
HELP!!
Can someone having this issue find out what the compilation rules are by Arduino IDE?

**Comment by jantje** [comment]
I'm just wondering..could it be Arduino IDE does not  compile .asm files?

**Comment by jantje** [comment]
I think this issue is close
