### ISSUE TITLE
can FreeRTOS be used with the ESP8266 in sloeber.

### ISSUE THREAD

**Issue by ghislainborremans** [Sloeber/arduino-eclipse-plugin#662]
Is there an example of FreeRTOS in sloeber?

**Comment by jantje** [comment]
Not that I'm aware of

**Comment by ghislainborremans** [comment]
FreeRTOS is in the libraries for the ESP8266 platform but it refers to AVR\io.h... . I suppose it is not meant to be there.

**Comment by jantje** [comment]
I had a look here and freertos is a library you can install in windows->preferences->arduino->library manager.
Once installed there are 3 examples available.
I tried analogread_digitalread and that compiles fine with the uno if you add the library manually.
Adding the library manually is needed because the include directive states Arduino_FreeRTOS.h and the foldername is FreeRTOS.
So yes there are examples for free rtos

**Comment by ghislainborremans** [comment]
I understand. i was looking to have it on ESP8266. 
I have now switched to  "taskscheduler".  ( https://github.com/arkhipenko/TaskScheduler)

**Comment by jantje** [comment]
The question "can freertos libary work with ESP8255" is for https://github.com/greiman/FreeRTOS-Arduino to answer. Not for sloeber.

**Comment by ghislainborremans** [comment]
ok
