### ISSUE TITLE
What is the error reason of "The plugin Needs write access to /private/var/folders/x5/..."?

### ISSUE THREAD

**Issue by yu66** [Sloeber/arduino-eclipse-plugin#666]
When i installed `http://eclipse.baeyens.it/update/V4/stable` in eclipse , And reopen it, it wrote 
```
The plugin Needs write access to 
/private/var/folders/x5/xdmx5m9n7dd_z6hd_hjrsk2h0000gn/T/AppTranslocation/2A44E398-5453-
42F5-8F29-C12371C8EF7B/d/Eclipse.app/Contents/Eclipse/arduinoPlugin
```
And then i uninstall it, re-install it, the error also happened.

The eclipse version is
```
Eclipse IDE for C/C++ Developers

Version: Neon.2 Release (4.6.2)
Build id: 20161208-0600
```

**Comment by jantje** [comment]
This is because the packages, libraries and other stuff sloeber uses to compile and upload sketches is downloaded by sloeber in the folder [eclipse location]/arduinoPlugin. 
Note that on mac you need to copy the download from the download folder due to mac security rules.

____
As an independent open source project we value your submission, but we ask for support, either by helping us out coding (yeah, we do understand it does require time) or a Patreon contribution (starting from as low as 1$ a month): this allows us to support people who support us back!
As a supporter you can drag our attention and prioritize your submission...
please become a supporter!
https://www.patreon.com/jantje
