### ISSUE TITLE
ATTinyCore - Sloeber won't change some settings (clock/B.O.D/Timer1 Clock)

### ISSUE THREAD

**Issue by liebman** [Sloeber/arduino-eclipse-plugin#827]
I found that changing the "Clock", "B.O.D" and "Timer 1 Clock" settings has no effect:
Here is the form I submitted (note I've set clock to 1 MHZ internal):
![screen shot 2017-09-20 at 3 30 51 pm](https://user-images.githubusercontent.com/1796060/30671046-db083690-9e19-11e7-8178-c5c791ba195b.png)

And here is the result opening properties again:
![screen shot 2017-09-20 at 3 30 30 pm](https://user-images.githubusercontent.com/1796060/30671079-050d6320-9e1a-11e7-9850-6ad45cb194f1.png)

**Comment by jantje** [comment]
I just tested here on the nightly and it works fine.
There has been some changes in this area because for upload to be working fine.
Did you just switched to the nightly? Because then Sloeber should have lost all settings but once you have re entered them all should be fine.
Just tested here with your setup.

**Comment by liebman** [comment]
Ok, I updated to a more recent nightly and its working fine now!  Thanks again.
