### ISSUE TITLE
"Check for updates" with nightly installed failes

### ISSUE THREAD

**Issue by liebman** [Sloeber/arduino-eclipse-plugin#905]
Error box is below available updates window:
<img width="876" alt="screen shot 2018-01-19 at 14 53 49" src="https://user-images.githubusercontent.com/1796060/35175631-67bbda6a-fd29-11e7-9db0-f30529c03230.png">

Info:
<img width="954" alt="screen shot 2018-01-19 at 14 59 15" src="https://user-images.githubusercontent.com/1796060/35175652-89136de0-fd29-11e7-8ad7-eb8e3c58dfce.png">

**Comment by jantje** [comment]
Hi @liebman 
First of all thanks for being a patron :-) It really is appreciated.
Yesterday I bumped into some upgrade issues myself and investigated I have not yet resolved the issue fully.
In your first image the details section is actually a multiline. So I can't be sure what it says, but I assume it complains about a dependency on gnumcueclipse and/or cdt version 9.4 for which no update sites are found.
The update sites are known by the Sloeber nightly update site but apparently not taken into account.
These update sites are
http://gnu-mcu-eclipse.netlify.com/v4-neon-updates
http://download.eclipse.org/tools/cdt/releases/9.4

Add these  2 update sites to your available update sites.

On my system it still didn't want to upgrade due to a dependency from sloeber.ide to (If I recall correctly 4.0 to a cdt version)
So I went for a install which told me I had to upgrade and it worked fine ... except for it is the latest nightly -1. I have not found why this is so.

Upgrade cdt https://github.com/Sloeber/arduino-eclipse-plugin/commit/4abf30b6ef32abd29b9dc2ad1e09737c95423dab
Upgrade gnuarm to gnumcu #898

**Comment by liebman** [comment]
Details say: "no remedy found" that's why I did not expand it.

Oh - my install was done installing CDT first, then adding the plugin. It's the same install I've been using for months.

Adding http://gnu-mcu-eclipse.netlify.com/v4-neon-updates as an update site fixed the issue.

**Comment by jantje** [comment]
I actually meant the other details :-)
![details](https://user-images.githubusercontent.com/1175841/35184140-e05d74e2-fdf1-11e7-8b4b-9d58946f892a.jpg)
