### ISSUE TITLE
ESP32 Program upload causes IDE to crash. 

### ISSUE THREAD

**Issue by kovachjk** [Sloeber/arduino-eclipse-plugin#999]
Trying to change from using Sloeber IDE which uploaded just fine to Sloeber Eclipse plugin
Sloeber IDE was in c:/arduino/sloeber.
Sloeber plugin is running on F:\cpp-oxygen and references libraries on c:\mysys32
test1: "hello world" compiles with no errors but when I try to upload the IDE crashes with the following errors.
![image](https://user-images.githubusercontent.com/9850342/42728087-09dc5fa8-8778-11e8-8c66-0ea3743cc40b.png)

**Comment by jantje** [comment]
You are probably missing something (or having a wrong version) in your install. That is why we do not officially support the plugin because it is not so easy to set things up properly.
Next to that there is no "functional advantage" to using the plugin apart from "adding Sloeber functionality to your existing environment"
